import { Doctor, VitalRecord, Prescription, Symptom } from './types';

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Sarah Jenkins',
    specialty: 'Cardiology',
    rating: 4.9,
    experience: 12,
    availability: ['09:00 AM', '10:30 AM', '02:00 PM', '03:30 PM'],
    avatarColor: 'teal',
  },
  {
    id: 'doc-2',
    name: 'Dr. Marcus Patel',
    specialty: 'Pediatrics',
    rating: 4.8,
    experience: 8,
    availability: ['11:00 AM', '01:00 PM', '03:00 PM', '04:30 PM'],
    avatarColor: 'blue',
  },
  {
    id: 'doc-3',
    name: 'Dr. Elena Rostova',
    specialty: 'General Medicine',
    rating: 4.9,
    experience: 15,
    availability: ['08:30 AM', '10:00 AM', '11:30 AM', '02:30 PM', '04:00 PM'],
    avatarColor: 'emerald',
  },
  {
    id: 'doc-4',
    name: 'Dr. David Kim',
    specialty: 'Dermatology',
    rating: 4.7,
    experience: 10,
    availability: ['09:30 AM', '01:30 PM', '04:00 PM'],
    avatarColor: 'indigo',
  },
  {
    id: 'doc-5',
    name: 'Dr. Alisha Warren',
    specialty: 'Orthopedics',
    rating: 4.8,
    experience: 14,
    availability: ['10:30 AM', '11:00 AM', '03:00 PM', '03:30 PM'],
    avatarColor: 'amber',
  },
];

export const INITIAL_VITALS: VitalRecord[] = [
  {
    id: 'v-1',
    date: 'Jul 01',
    time: '08:30 AM',
    systolic: 120,
    diastolic: 80,
    heartRate: 72,
    temperature: 98.6,
  },
  {
    id: 'v-2',
    date: 'Jul 02',
    time: '09:00 AM',
    systolic: 122,
    diastolic: 81,
    heartRate: 75,
    temperature: 98.4,
  },
  {
    id: 'v-3',
    date: 'Jul 03',
    time: '08:45 AM',
    systolic: 118,
    diastolic: 78,
    heartRate: 68,
    temperature: 98.6,
  },
  {
    id: 'v-4',
    date: 'Jul 04',
    time: '09:15 AM',
    systolic: 124,
    diastolic: 83,
    heartRate: 80,
    temperature: 99.1,
  },
  {
    id: 'v-5',
    date: 'Jul 05',
    time: '08:30 AM',
    systolic: 121,
    diastolic: 79,
    heartRate: 73,
    temperature: 98.5,
  },
  {
    id: 'v-6',
    date: 'Jul 06',
    time: '09:00 AM',
    systolic: 119,
    diastolic: 78,
    heartRate: 71,
    temperature: 98.2,
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-1',
    name: 'Lisinopril',
    dosage: '10 mg',
    frequency: 'Once Daily (Morning)',
    takenToday: false,
    refillStatus: 'none',
    remainingRefills: 2,
    scheduledTimes: ['09:30 AM'],
  },
  {
    id: 'rx-2',
    name: 'Atorvastatin',
    dosage: '20 mg',
    frequency: 'Once Daily (Bedtime)',
    takenToday: false,
    refillStatus: 'none',
    remainingRefills: 1,
    scheduledTimes: ['10:00 PM'],
  },
  {
    id: 'rx-3',
    name: 'Amoxicillin',
    dosage: '500 mg',
    frequency: 'Twice Daily (with Food)',
    takenToday: false,
    refillStatus: 'none',
    remainingRefills: 0,
    scheduledTimes: ['09:00 AM', '06:00 PM'],
  },
];

export const SYMPTOMS_LIST: Symptom[] = [
  { id: 'sym-1', name: 'Mild Headache', severity: 'mild', category: 'General' },
  { id: 'sym-2', name: 'Severe Migraine', severity: 'severe', category: 'General' },
  { id: 'sym-3', name: 'Low Grade Fever (< 100.4°F)', severity: 'mild', category: 'General' },
  { id: 'sym-4', name: 'High Fever (> 101.5°F)', severity: 'severe', category: 'General' },
  { id: 'sym-5', name: 'Mild Dry Cough', severity: 'mild', category: 'Respiratory' },
  { id: 'sym-6', name: 'Shortness of Breath', severity: 'severe', category: 'Respiratory' },
  { id: 'sym-7', name: 'Mild Sore Throat', severity: 'mild', category: 'Respiratory' },
  { id: 'sym-8', name: 'Chest Pain or Tightness', severity: 'severe', category: 'Cardiovascular' },
  { id: 'sym-9', name: 'Mild Muscle Aches', severity: 'mild', category: 'Musculoskeletal' },
  { id: 'sym-10', name: 'Severe Joint Swelling', severity: 'moderate', category: 'Musculoskeletal' },
  { id: 'sym-11', name: 'Nausea or Indigestion', severity: 'mild', category: 'Digestive' },
  { id: 'sym-12', name: 'Sudden Dizziness/Fainting', severity: 'severe', category: 'General' },
];
